name: Meu Primeiro CI -- MASTER

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  GrupoTeste:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Primeira Tarefa MAIN
        run: echo Executando o que solicitei!

      - name: Segunda Tarefa
        run: |
          echo Segundo comando em execucao.
          echo Projeto Teste!
